### ISSUE TITLE
Add installation instructions for Tensorflow 2.0 Beta

### ISSUE THREAD

**Issue by rjurney** [tensorflow/hub#354]
I once installed Tensorflow Hub for Tensorflow 2.0 Beta (or maybe the nightly build?) and it worked but I can't recall or find any instructions for how to get Tensorflow Hub to work with tf 2.0. What I remember is there is a particular branch or something you install rather than the standard 0.5.0 package but I can't find it anywhere.

I get this error when I try to import `tensorflow_hub`:

```python
import tensorflow as tf
import tensorflow_hub as hub
```

```python
AttributeError: module 'tensorflow_hub.tf_v1' has no attribute 'estimator'
```

My environment is Anaconda Python 3.6.8:

```bash
pip freeze|egrep 'tf|tensor'
```

```python
tensorflow-estimator-2.0-preview==1.14.0.dev2019081901
tensorflow-hub==0.5.0
tf-nightly-gpu-2.0-preview==2.0.0.dev20190819
```

How do you install Tensorflow Hub for TF 2.0 Beta/Nightly? Which one is required?

**Comment by rmothukuru** [comment]
@rjurney ,
Please find the working code mentioned below for installing `TF Hub` for `Tensorflow 2.0.0-beta`.

```
!pip install "tensorflow_hub==0.5.0"
!pip install tensorflow==2.0.0-beta

import tensorflow as tf
import tensorflow_hub as hub

print(tf.__version__)

module_url = "https://tfhub.dev/google/tf2-preview/nnlm-en-dim128/1"
embed = hub.KerasLayer(module_url)
embeddings = embed(["A long sentence.", "single-word", "http://example.com"])
print(embeddings.shape)  #(3,128)
```

**Comment by rjurney** [comment]
@rmothukuru thanks, is the website tensorflow.org a github repo so I can add this to the documentation?

**Comment by rmothukuru** [comment]
@rjurney ,
Got it. We'll keep this request open and will check the possibility of updating the tensorflow.org website.

**Comment by andresusanopinto** [comment]
tensorflow.org/hub now shows the correct installing instructions.

Also the original issue with "tf_v1" missing the estimator symbol was due to a "tf-nightly" issue and not due to a mistmatch versions to install.
