### ISSUE TITLE
Cannot import tensorflow hub

### ISSUE THREAD

**Issue by Bannigo** [tensorflow/hub#819]
Hello Guys,

I am facing an issue regarding the import of TensorFlow hub.  Following are the errors which are posted in the terminal. The version of tensorflow, I am using is 2.6, and the version of tensorflow-hub is 0.12.0. I installed both of them using pip install. I have a bit of urgency in completing my project, and I would be really thankful for your help. 

 File "/home/bannigo/catkin_ws/src/motorAI_assign/scripts/task1_1.py", line 21, in <module>
    import tensorflow_hub as hub
  File "/home/bannigo/.local/lib/python3.6/site-packages/tensorflow_hub/__init__.py", line 88, in <module>
    from tensorflow_hub.estimator import LatestModuleExporter
  File "/home/bannigo/.local/lib/python3.6/site-packages/tensorflow_hub/estimator.py", line 62, in <module>
    class LatestModuleExporter(tf.compat.v1.estimator.Exporter):
  File "/home/bannigo/.local/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/home/bannigo/.local/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/bannigo/.local/lib/python3.6/site-packages/tensorflow_estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/home/bannigo/.local/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "/home/bannigo/.local/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py", line 10, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/home/bannigo/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py", line 27, in <module>
    from tensorflow_estimator.python.estimator import estimator
  File "/home/bannigo/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 70, in <module>
    @doc_controls.inheritable_header("""\
AttributeError: module 'tensorflow.tools.docs.doc_controls' has no attribute 'inheritable_header'

**Comment by ZheZhangTUD** [comment]
I got exact same problem. I'm looking for help. 
Python 3.79
tensorflow: 2.6
tensorflow_hub: 0.12

**Comment by DavidRalph** [comment]
Same problem.
Python 3.6
tensorflow 2.6.0
tensorflow_hub 0.12.0

Works fine with tensorflow 2.5.1

**Comment by ZheZhangTUD** [comment]
I reinstalled tensorflow, tensorflow_hub, degraded to tensorflow 2.5.0 , tensorflow_hub 0.12.0. The problem disappeared.

**Comment by WGierke** [comment]
The TF team is currently working on a fix. In the meantime, please try downgrading tensorflow-estimator:
```bash
pip install -U tensorflow-estimator==2.6.0
```

**Comment by UsharaniPagadala** [comment]
@Bannigo 

Could you respond to the above comment by @WGierke 
 also please refer to the similar [issue](https://stackoverflow.com/questions/69794473/module-tensorflow-tools-docs-doc-controls-has-no-attribute-inheritable-header), and let us know if this helps.Thanks

**Comment by FindTheConstraint** [comment]
> ```shell
> pip install -U tensorflow-estimator==2.6.0
> ```

This is now giving the error: AlreadyExistsError: Another metric with the same name already exists.

**Comment by WGierke** [comment]
Please try downgrading keras:
```bash
pip install -U keras==2.6.0
```
The TF team just released v2.7.0 (https://pypi.org/project/tensorflow/). In preparation for that, other libraries had to release their new versions 2.7.0 first (tensorflow-estimator, keras, ...). It occasionally happened that when installing TF 2.6, some dependencies were installed with their new version 2.7.0. This led to issues since the combination of TF 2.6 and version 2.7 of these libraries is not compatible. @FindTheConstraint please tell us whether downgrading keras helped.

**Comment by Bannigo** [comment]
Hi everyone,
Thank you so much for your inputs. I had to go offline due to a few circumstances. But the solution works now. I have downgraded TensorFlow.

**Comment by UsharaniPagadala** [comment]
@Bannigo 
Closing this issue as it is resolved.Please feel free to reopen if this still exists.Thanks

**Comment by farhaddubey** [comment]
!pip install --upgrade tensorflow-hub 
In jupyter notebook it worked.
Either downgrade the tensorflow or upgrade the tensorflow-hub.
