### ISSUE TITLE
Using ELMo with TensorFlow 2.0

### ISSUE THREAD

**Issue by basroelenga** [tensorflow/hub#412]
Is it possible to use ELMo as a embedding layer with hub.KerasLayer? 

If i try:

```
import tensorflow_hub as hub
import tensorflow as tf

input_tokens = tf.keras.layers.Input(shape=(1000,), name="input_tokens", dtype="string")
sequence_length = tf.constant([1000])

elmo_layer = hub.KerasLayer('https://tfhub.dev/google/elmo/3',
                            signature='tokens',
                            output_key='elmo',
                            trainable=True)

embedding_tokens = elmo_layer(inputs={'tokens': input_tokens,
 'sequence_len': sequence_length})
```

I get the following error message:
`_SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'input_tokens_9:0' shape=(None, 1000) dtype=string>]`

Is there something I am missing here or is it not possible yet?

**Comment by gowthamkpr** [comment]
@basroelenga ELMO is not available in Tensorflow 2.0 yet but you can use hub.KerasLayer with Tensorflow 1.15 and it works without any error. Please find the gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/f01a548c4faa4088e476c727f693091b/untitled235.ipynb)

**Comment by basroelenga** [comment]
@gowthamkpr Thnx for your response! I indeed got it working in TF 1.15 and was just wondering if it was possible in TF2.0. Is there any timeline for when this will be updated for TF2? Or is it just a waiting game?

**Comment by gowthamkpr** [comment]
@basroelenga Can't give a concrete timeline but keep the community posted on the updates. Closing this issue as it has been resolved.

**Comment by simonjuleseric2** [comment]
Is elmo available with TF2 now?

**Comment by arnoegw** [comment]
Unfortunately, there is nothing but what you can find at https://tfhub.dev/s?q=elmo which is ELMo for TF1.

**Comment by popkristina** [comment]
Any news on when using a trainable elmo on tensorflow 2 will be possible? Or did anyone figure this out in meantime?

**Comment by anisha-learner** [comment]
Does Tensorflow 2.0 support elmo embeddings now? I am still getting the error   AttributeError: 'NoneType' object has no attribute 'outer_context'
If I try to run on Google collab by installing tensorflow 1.15 I get  ERROR: No matching distribution found for tensorflow==1.15

**Comment by srinivaslakshman20** [comment]
The below code should work on the new tensor flow version.

============================================
import tensorflow as tf
import tensorflow_hub as hub
import numpy as np


elmo = hub.load("https://tfhub.dev/google/elmo/2").signatures["default"]

x = ["Hello world!"]
embeddings = elmo(tf.constant(x))["elmo"]

print(embeddings.shape)
print(embeddings.numpy())

============================================
